language: php

dist: trusty
sudo: false

php:
  - '7.0'
  - '7.1'
  - '7.2'

matrix:
  fast_finish: true
  include:
    - php: '7.0'
      env: SYMFONY_VERSION='3.2.*'
    - php: '7.0'
      env: SYMFONY_VERSION='3.3.*'
    - php: '7.0'
      env: SYMFONY_VERSION='3.4.*'
    - php: '7.1'
      env: SYMFONY_VERSION='3.4.*'
    - php: '7.1.3'
      env: SYMFONY_VERSION='4.0.*'
    - php: '7.2'
      env: SYMFONY_VERSION='3.4.*'
    - php: '7.2'
      env: SYMFONY_VERSION='4.0.*'

before_install:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi

install:
  - composer update $COMPOSER_FLAGS --prefer-dist --prefer-stable

script:
  - vendor/bin/simple-phpunit
